# Scalar

In [17]:
x = 'salman'
x

'salman'

In [18]:
type(x)

str

In [19]:
y = "arya"

In [22]:
sum = x + ' ' + y
sum

'salman arya'

# Vector

In [23]:
import numpy as np

In [24]:
x = np.array([25, 2, 5])

In [26]:
x

array([25,  2,  5])

In [28]:
len(x)

3

In [29]:
x.shape

(3,)

In [30]:
type(x)

numpy.ndarray

In [31]:
x[1]

2

In [33]:
type(x[0])

numpy.int32

# Vector Transpose

In [42]:
import numpy as np
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [43]:
y.shape

(1, 3)

In [46]:
y_t = np.transpose(y)
y_t

array([[25],
       [ 2],
       [ 5]])

In [47]:
y_t_baru = y.T
y_t_baru

array([[25],
       [ 2],
       [ 5]])

In [48]:
y_t_baru.shape

(3, 1)

### $L^2$ Norm

In [5]:
# vector [25, 2, 5]
# 1. pangkatkan setiap nilai dari vector
# 2. hasil pangkat dijumlahkan
# 3. hasil dari penjumlahan kita ambil akarnya

(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [6]:
import numpy as np
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [7]:
np.linalg.norm(x)

25.573423705088842

In [8]:
# mas ferdi
# expected 25.573
round(np.linalg.norm(x),3)

25.573

### $L^1$ Norm

In [ ]:
# ambil ambsolute value yang di vector [25, 2, 5]
# jumlahkan hasil dari masing-masing absolute value [25, 2, 5]

np.abs(25) + np.abs(2) + np.abs(5)

32

### Squred $L^2$ Norm

In [12]:
# vector [25, 2, 5]
# 1. pangkatkan setiap nilai dari vector
# 2. hasil pangkat dijumlahkan 

(25**2 + 2**2 + 5**2) 

654

In [17]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [14]:
np.dot(x, x)

654

### Max Norm

In [19]:
# 1. ambil absolute dari vector value [25,  2,  5]
# 2. ambil nilai index yang maksimum dari vector values
import numpy as np
np.max([np.abs(25), np.abs(2), np.abs(5)])

# expected output 25

25

In [18]:
# mas faza
np.max(x)

25