# Scalar

In [17]:
x = 'salman'
x

'salman'

In [18]:
type(x)

str

In [19]:
y = "arya"

In [22]:
sum = x + ' ' + y
sum

'salman arya'

# Vector

In [23]:
import numpy as np

In [24]:
x = np.array([25, 2, 5])

In [26]:
x

array([25,  2,  5])

In [28]:
len(x)

3

In [29]:
x.shape

(3,)

In [30]:
type(x)

numpy.ndarray

In [31]:
x[1]

2

In [33]:
type(x[0])

numpy.int32

# Vector Transpose

In [42]:
import numpy as np
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [43]:
y.shape

(1, 3)

In [46]:
y_t = np.transpose(y)
y_t

array([[25],
       [ 2],
       [ 5]])

In [47]:
y_t_baru = y.T
y_t_baru

array([[25],
       [ 2],
       [ 5]])

In [48]:
y_t_baru.shape

(3, 1)